# Generated by Django 5.0.3 on 2024-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default_profile.jpeg', upload_to='user_photos/'),
        ),
    ]
