# Generated by Django 5.0.3 on 2024-04-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
